[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = ["pulldown-kdl/debug"]

[dependencies]
lexopt = "0.3.0"
miette = { version = "7.4.0", features = ["fancy"] }
pulldown-kdl = { version = "0.1.0", path = "../pulldown-kdl" }
serde_json = "1.0.133"
